### ISSUE TITLE
Spam 3d clothes

### ISSUE THREAD

**Issue by Paradox75831004** [BunyaPineTree/LethalCompany_ModelReplacementAPI#64] opened 2024-02-05 08:46 UTC
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/72872478/e1210019-375d-4948-9757-ed08a2153193)
018d7872-1c95-a8da-e12e-690bbbc52eaf
What is it about?

**Comment by lil-fluff** [comment] 2024-02-05 19:19
This error is thrown on Build 2.3.6 as well:

`[Info   :   Console] Exception in MoreCompanyRenderCosmetcs on Player  System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component.get_transform(UnityEngine.Component)
  at ModelReplacement.Modules.MoreCompanyCosmeticManager.DangerousRenderCosmetics (System.Boolean useAvatarTransforms) [0x000e4] in <b9ae5003cd51460481d20a5bd9c6d186>:0 
  at ModelReplacement.Modules.MoreCompanyCosmeticManager.SafeRenderCosmetics (System.Boolean useAvatarTransforms) [0x00002] in <b9ae5003cd51460481d20a5bd9c6d186>:0 `
  
  Currently investigating the cause.

**Comment by lil-fluff** [comment] 2024-02-05 20:49
A fairly obvious issue is that the cosmeticTransformPairs are not getting loaded properly in line [65 in MoreCompanyCosmeticManager.cs 
](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/blob/05af70d11208fbac4f0ab63bbc66e4b0eae53e55/ModelReplacementAPI/Modules/MoreCompanyCosmeticManager.cs#L65) 
The line should be reverted to `if (cosmeticTransformPairs.Count != 0) return;`
Otherwise, the dictionary values are not initialized and the length will *always* return 0.

Further down, it seems that [setting the parent of cosmeticInstance.transform](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/blob/05af70d11208fbac4f0ab63bbc66e4b0eae53e55/ModelReplacementAPI/Modules/MoreCompanyCosmeticManager.cs#L109) causes the cosmeticInstance itself to dereference, as it would always become null in my testing. This happens if you set the parent to null or if you copy what MoreCompany mod does: `cosmeticInstance.transform.parent = transform;`

Commenting out line 109 yields.... unwanted behaviour. It works, in that the console no longer throws errors, and the cosmetic item does appear and track with the model, but then the offsets go all weird because the offsets are calculated expecting the transform parent to be empty...

For now, I have uploaded a build to my fork of the mod with the entire class patched out to avoid unwanted console spam. It relies on the default offsets of scav model, so if your custom model isn't too close to the base model, cosmetics will look weird and clip a lot.

**Comment by BunyaPineTree** [comment] 2024-02-25 01:44
The console spam should be fixed in the latest release. I will be closing this as the cosmetics issue in general has also been fixed in experimental, and won't be released until changes to the SDK are made.

**Closed by BunyaPineTree** 2024-02-25 01:44 UTC
