### ISSUE TITLE
Miku causes massive fps drops

### ISSUE THREAD

**Issue by Antside** [BunyaPineTree/LethalCompany_ModelReplacementAPI#4] opened 2023-12-08 06:48 UTC
So even with just 3 people, this model causes massive fps drops. It is basically unplayable. However, this didn't happen right off the bat and started after being in the ship for a bit. Is anyone else having this issue? Was wondering if we could maybe get a skin with no hair mechanics so that it helps fps and that we dont get those glitchy hair physics.

**Comment by BunyaPineTree** [comment] 2023-12-08 07:55
I've released a new version that has config options to set some dynamic bone parameters (update rate, disable at range, distance to disable at range). 

I can confirm that reducing the update rate from default 60 to 20 makes a lobby with 9 people vaguely playable as opposed to mission impossible, so set them to whatever works for you.

**Comment by BunyaPineTree** [comment] 2023-12-08 08:32
A mod list would be useful. I'm not getting that issue myself.

**Comment by Antside** [comment] 2023-12-08 09:08
Ok, thank you very much

**Comment by BunyaPineTree** [comment] 2023-12-14 00:12
There turned out to be some unsafe code in the MoreCompany support that was causing this issue, closing as it has since been fixed.

**Closed by BunyaPineTree** 2023-12-14 00:12 UTC
