### ISSUE TITLE
Can't see MoreCompany cosmetics on my friends custom models

### ISSUE THREAD

**Issue by mehAeon** [BunyaPineTree/LethalCompany_ModelReplacementAPI#45] opened 2024-01-14 02:31 UTC
I can see them in the ship camera on myself, but not on other people.

**Comment by BunyaPineTree** [comment] 2024-01-14 03:06
Thanks for posting the issue. I was actually playing earlier today to test a model and saw both visible corpses and MoreCompany cosmetics. 
Could you get me your mod list, or even just your r2modman profile code? 
Of course if you didn't have any other mods installed at all then you don't need to. I use a number of mods for convenience when testing models that affect rendering.

**Comment by mehAeon** [comment] 2024-01-14 04:03
Mods that we used: hdlethalcompany, lethal clunk, lethalconfig, lethalexpansioncore, lethalthings, mmhook, morecompanycosmetics, morecompany, moresuits, thicccompanymodelreplacement, thiccwomansuit, resAdditionalSuits, scp173, terminalstuff, chillaxmods, cozyimprovements, controlcompany, doorfix, fairAI, fovadjust, hideplayernames, helmetcamera, kindteleporters, latecompany, terminalcommands, letmelookdown, maskedenemyrework, mimics, modelreplacementapi, morecompany, moreemotes, moreitems, RuntimeNetcodeRPCValidator, BepInExUtils, ControlDeathVoting, skinwalkermod, spectateenemy, terminalextras, yippeemod, 3rdPerson.

**Comment by BunyaPineTree** [comment] 2024-02-25 01:47
The cause for this issue is known and has been addressed in experimental, but won't be released until changes to the SDK are made.

**Closed by BunyaPineTree** 2024-02-25 01:47 UTC
