### ISSUE TITLE
V: 2.3.2 is incompatible with the Mod Too Many Emotes

### ISSUE THREAD

**Issue by James-Molzer** [BunyaPineTree/LethalCompany_ModelReplacementAPI#25] opened 2024-01-05 19:32 UTC
previous versions before 2.3.2 had no issues but with 2.3.2 when using Too Many Emotes, when the player uses a emote there is a visual bug that happens. there seems to be a 3rd person camera overlap that blurs the player's view as well as seeing the players arms floating in the air that are separate from the the characters model that is preforming the emote.

Steps to reproduce the bug:

1.have Too Many Emotes installed along with V 2.3.2

2. After hosting a game activate the hotkey for too many emotes and select a emote to use

**Comment by Edouard127** [comment] 2024-01-05 20:51
Bump, also happens on my side, but it may be caused by incorrect model configuration

**Comment by BunyaPineTree** [comment] 2024-01-06 05:19
This should be fixed in the most recent update. Let me know if it persists.

**Closed** 2024-01-07 19:35 UTC
