### ISSUE TITLE
MaskedEnemyOverhaul mod uses "default" body instead of the thicc one

### ISSUE THREAD

**Issue by ConnaKazie** [BunyaPineTree/LethalCompany_ModelReplacementAPI#65] opened 2024-02-05 17:01 UTC
Would it be possible to make the MaskedEnemyOverhaul enemies use the thicc model when mimicking a player that has a thicc model enabled? Or should I bring this to that mod page? I don't know which mod would need to create the compatibility.

**Comment by BunyaPineTree** [comment] 2024-02-05 19:24
That's currently being worked on very slowly. The issue is that it requires the entire framework of enemy body replacements to be built as well, so don't expect it any time soon.

**Comment by NeatWolf** [comment] 2024-03-21 20:51
Same happens with LethalCreature - I see there's an experimental branch here going on tho?
Having mimics run around with a different model is, well, pretty gamebreaking.

**Comment by BunyaPineTree** [comment] 2024-04-01 07:44
MaskedEnemyOverhaul compatibility is still unknown since I haven't tested it together, but the next update will have masked support, so I'll close this issue for now.

**Closed by BunyaPineTree** 2024-04-01 07:44 UTC
